import { MD_RENDER_ALLOWED_TAGS, MD_RENDER_ALLOWED_ATTRIBUTES } from '$lib/markdown/renderMarkdownSafe';

export { MD_RENDER_ALLOWED_TAGS as RICH_TEXT_ALLOWED_TAGS };
export { MD_RENDER_ALLOWED_ATTRIBUTES as RICH_TEXT_ALLOWED_ATTRIBUTES };
